# Generated by Django 6.0.3 on 2026-03-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='GoGreenTech Learning Academy', max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('intro_text', models.TextField()),
                ('intro_video_urls', models.JSONField(blank=True, default=list)),
                ('why_choose_us', models.JSONField(blank=True, default=list)),
                ('learning_modes', models.JSONField(blank=True, default=list)),
                ('owner_name', models.CharField(default='Rashid Zada', max_length=120)),
                ('owner_role', models.CharField(default='Software Engineer', max_length=120)),
                ('owner_email', models.EmailField(default='rashidzad6@gmail.com', max_length=254)),
                ('owner_whatsapp', models.CharField(default='03470983567', max_length=20)),
                ('owner_qualification', models.CharField(blank=True, max_length=180)),
                ('footer_note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Homepage content',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
