# Generated by Django 6.0.3 on 2026-03-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeLearningVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(unique=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("language", models.CharField(default="Pashto", max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(default=True)),
                ("show_on_homepage", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
