# Generated by Django 6.0.3 on 2026-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_freelearningvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='about_description',
            field=models.TextField(default='GoGreenTech Learning Academy is designed for students who want real skill development without a heavy or confusing learning system. The owner, Rashid Zada, combines software engineering experience with a simple teaching model: structured content, preview access, clear enrollment, and direct support.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title',
            field=models.CharField(default='A practical learning platform built around guided progress', max_length=220),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='owner_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='owner_profile_url',
            field=models.URLField(blank=True, default='https://rashidzada.pythonanywhere.com/'),
        ),
    ]
