# Generated by Django 6.0.3 on 2026-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepagecontent_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='website/owners/'),
        ),
    ]
