# Generated by Django 6.0.3 on 2026-03-08 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('admin', 'Admin'), ('direct', 'Direct')], default='direct', max_length=20)),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('quiz', 'Quiz'), ('resource', 'Resource'), ('course', 'Course Update'), ('announcement', 'Announcement')], default='announcement', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
