from io import BytesIO
from pathlib import Path

from django.conf import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from common.utils import build_whatsapp_url


def build_course_whatsapp_message(course_title: str, student_name: str = "", email: str = "") -> str:
    intro = f"Assalamualaikum, I am interested in the course {course_title}."
    details = []
    if student_name:
        details.append(f"My name is {student_name}.")
    if email:
        details.append(f"My email is {email}.")
    details.append("Please guide me about enrollment and pricing.")
    return " ".join([intro, *details])


def build_course_whatsapp_url(course_title: str, student_name: str = "", email: str = "") -> str:
    return build_whatsapp_url(
        settings.WHATSAPP_NUMBER,
        build_course_whatsapp_message(course_title, student_name, email),
    )


def _invoice_logo_path() -> Path:
    return Path(settings.BASE_DIR) / "static" / "branding" / "gogreentech_logo.png"


def build_invoice_pdf(payment):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    pdf.setTitle(payment.invoice_number)

    logo_path = _invoice_logo_path()
    if logo_path.exists():
        pdf.drawImage(
            str(logo_path),
            50,
            776,
            width=42,
            height=42,
            mask="auto",
            preserveAspectRatio=True,
        )

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(104, 800, "GoGreenTech Learning Academy")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(104, 782, f"Invoice: {payment.invoice_number}")
    pdf.drawString(50, 766, f"Course: {payment.enrollment.course.title}")
    pdf.drawString(50, 750, f"Student: {payment.enrollment.user.full_name}")
    pdf.drawString(50, 734, f"Email: {payment.enrollment.user.email}")
    pdf.drawString(50, 718, f"Payment method: {payment.get_payment_method_display()}")
    pdf.drawString(50, 702, f"Status: {payment.get_status_display()}")

    pdf.setStrokeColor(colors.HexColor("#1f7a4d"))
    pdf.line(50, 690, 540, 690)

    rows = [
        ("Amount due", f"PKR {payment.amount_due}"),
        ("Amount paid", f"PKR {payment.amount_paid}"),
        ("Balance", f"PKR {payment.balance}"),
        ("Reference", payment.transaction_reference or "N/A"),
    ]

    current_y = 660
    pdf.setFont("Helvetica-Bold", 12)
    for label, value in rows:
        pdf.drawString(60, current_y, label)
        pdf.setFont("Helvetica", 12)
        pdf.drawRightString(520, current_y, value)
        current_y -= 28
        pdf.setFont("Helvetica-Bold", 12)

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, 120, "This invoice is generated by the GoGreenTech platform.")
    pdf.drawString(50, 104, f"Contact: {settings.WHATSAPP_NUMBER}")

    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    return buffer
